---
- include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "{{ ansible_os_family|lower }}.yml"
        - "default.yml"
      paths:
        - 'vars'
  tags:
    - samba

- include: install_debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - samba

- include: configure.yml
  tags:
    - samba
